### ISSUE TITLE
git apply  FreeRTOS-LoRaMac-node-v4_4_4.patch not working

### ISSUE THREAD

**Issue by cawahe** [FreeRTOS/Lab-Project-FreeRTOS-LoRaWAN#2]
Hello, when applying patch I cannot get it working. when in the correct project directory

`error: LoRaMac-node/src/mac/LoRaMac.h: No such file or directory
error: LoRaMac-node/src/mac/LoRaMacHeaderTypes.h: No such file or directory
error: LoRaMac-node/src/radio/radio.h: No such file or directory
error: LoRaMac-node/src/radio/sx126x/radio.c: No such file or directory
error: LoRaMac-node/src/system/timer.h: No such file or directory`

**Comment by butlerpaul** [comment]
Did you forget "--recurse-submodules" when you cloned the repo?  The error message sounds like you may be missing the submodules.

**Comment by cawahe** [comment]
Thanks. that did it!
