### ISSUE TITLE
How to use this repository with esp32?

### ISSUE THREAD

**Issue by horsemann07** [FreeRTOS/Lab-Project-FreeRTOS-LoRaWAN#7]
Hello,
Right now, current **Lab-Project-FreeRTOS-LoRaWAN** supports only st and Nordic boards. 
I want to use this repository with esp32 (esp-idf).I searched for documentation of this repository so I could start implenting with esp-idf, But I didn't find anyone. 

Now, I not getting any idea from where should I start?

Can any one guide me?
If I start implementing for esp32 what changes I have to make and from where I have to start?. What are the things I have to do? 

I will be very thankful if anyone will explain in detail of procedures.

```
OS: Linux
Boards: esp32
IDF: esp-idf
LoRa Module: SX1278 LoRa RF Module
```

**Comment by jasonpcarroll** [comment]
Hi @Raghav3107,
Thank you for reaching out. I will reach out to the team and see what their thoughts are.

**Comment by jasonpcarroll** [comment]
Hi @Raghav3107,
I am working on a buildable port of this demo to the ESP32. I do not have an SX1278, so I may need some information from you and for you test my port. Could you let me know how you are connecting the ESP32 to the SX1278? I'm assuming you are using SPI.

**Comment by horsemann07** [comment]
Hello @jasonpcarroll 

Thanks for the help and building the demo for ESP32.
I will happy to help you!!.


> Could you let me know how you are connecting the ESP32 to the SX1278? I'm assuming you are using SPI.

Yeah! I m using the SPI to communicate with SX1278. Also, I m using following library for simple lora receiver and sender with esp32 for now.
[https://github.com/Inteform/esp32-lora-library](https://github.com/Inteform/esp32-lora-library).

Also I just want some confirmation from you. Does this demo only supports  the Class A? Or It also supports Class B?

**Comment by jasonpcarroll** [comment]
Currently, this demo only supports Class A.

**Comment by horsemann07** [comment]
Hello @jasonpcarroll ,
Can you tell me, when will esp demo of this repository complete? approx?

**Comment by jasonpcarroll** [comment]
I apologize for the delayed response - I have been busy with a few things and had to push this. I cannot give you a guaranteed ETA, but I will try to have it sometime this week.

**Comment by horsemann07** [comment]
No need for apologize @jasonpcarroll . 

I want some idea how can for require project. 

Requirement:

There is 100 Lora edge node which will transmit some data to one super node which will transmit same data to gateway. Also, gateway send ack to supernode and supernode send ack to end node.
I check this repository and its support only class A ( which send end node data to cloud ). 

1. How can I manage to full this requirement using this repository?

Any input will be helpful.

Thanks!!!

**Comment by horsemann07** [comment]
Hello @jasonpcarroll  


> Hi @Raghav3107, I am working on a buildable port of this demo to the ESP32. I do not have an SX1278, so I may need some information from you and for you test my port. Could you let me know how you are connecting the ESP32 to the SX1278? I'm assuming you are using SPI.

can you give me any update on this?

**Comment by dachalco** [comment]
Hi @Raghav3107 

You should be able to port to esp32 with the sx1278. Presumably the chip is mounted on a board, with some subset of the chip's GPIO exposed? Typically consists of SPI link and some GPIO in/out signals for interrupts and triggers. Given the esp32 has all of these interfaces, it should be possible, but I'm unable to find an existing example so new code is needed.

This particular LoRa stack has a porting guide available [here](https://stackforce.github.io/LoRaMac-doc/LoRaMac-doc-v4.5.1/_p_o_r_t_i_n_g__g_u_i_d_e.html). You'll need to create new interface for the chip, using esp32, similar to what is done [here](https://github.com/Lora-net/LoRaMac-node/blob/master/src/boards/NucleoL073/sx1261mbxbas-board.c), implementing the necessary `Spi*()` and `Gpio*()` functions in a similar fashion but with Espressif's HAL. Once these interfaces are defined, you can tie up to the rest of the LoRa stack.

**Comment by horsemann07** [comment]
Hello @dachalco 

Thanks for the guidance. 
I will check the guide and try to port to esp32.
