### ISSUE TITLE
Problem when region is set to LORAMAC_REGION_EU868

### ISSUE THREAD

**Issue by zzolax** [FreeRTOS/Lab-Project-FreeRTOS-LoRaWAN#8]
Hello,
I have nRF52840DK and SX1621MB2xAS, when region is default looks that all is ok but when change it (to any other) there is:

0 0 [LoRaWanClassA] ###### ===== Class A LoRaWAN application ==== ######

1 0 [LoRaWanClassA] Failed to initialize lorawan error = 9
2 0 [LoRaWanClassA] Failed to join to a lorawan network, error = 9

What can cause this?
The result is the same whether the PCB with the radio is placed or not.

**Comment by zzolax** [comment]
Fixed, had to change project file:
<configuration
      Name="Debug"
      arm_linker_variant="GNU"
      c_preprocessor_definitions="__SIZEOF_WCHAR_T=4 ;__ARM_ARCH_7EM__;__SES_ARM;__ARM_ARCH_FPV4_SP_D16__;DEBUG;DEBUG_NRF;NRF52840_XXAA;BOARD_PCA10056;LORAWAN_USE_EXTERNAL_TIMERS;APP_ENTRY_POINT=main;__FREERTOS;SDK_MUTEX_ENABLE;SWI_DISABLE0;SVC_INTERFACE_CALL_AS_NORMAL_FUNCTION;RETARGET_ENABLED;INITIALIZE_USER_SECTIONS;FLOAT_ABI_HARD;ENABLE_DEBUG_LOG_SUPPORT;CONFIG_GPIO_AS_PINRESET;**REGION_EU868**"

To have ABP mode (not OTAA) have to do something more than:
 if( status == LORAMAC_STATUS_OK )
    {
        configPRINTF( ( "Initiating OTAA join procedure.\r\n" ) );
       // status = LoRaWAN_Join();
      **status =  LoRaWAN_ActivateByPersonalization();**
    }
and set correct values in credentials.c ?

**Comment by ravibhagavandas** [comment]
Hi @zzolax 
You are right. In addition to calling the API `LoRaWAN_ActivateByPersonalization()`, you need to set the credentials `devEUI, joinEUI, appSessionKey, nwkSessionKey, END_DEVICE_ADDR` in [credenitals.c]( https://github.com/FreeRTOS/Lab-Project-FreeRTOS-LoRaWAN/blob/master/demos/classA/common/credentials.c) to activate using ABP.

**Comment by zzolax** [comment]
Hello @ravibhagavandas,
thank you for the answer. OTAA works great but in ABP gateway (RAK7258) sends periodically "NewChannelReq" - for each uplink
![abp](https://user-images.githubusercontent.com/59441877/148954842-a5709441-cdce-4ab6-bb0a-d09a246eee14.jpg)

**Comment by dachalco** [comment]
Hi @zzolax, 
The changing of channels you see -- frequency hopping -- is a feature of LoRaWAN stack that's done for FCC compliance and also allows lora server to prevent bombardment on a single channel by devices at scale. It is possible to limit the lora radio to a single channel if you're using a custom lora server, but not suggested for compatibility with a variety of lora servers and frequency plans such as TTN.

**Comment by zzolax** [comment]
Hello @dachalco, thanks for the answer but I have many other Lora nodes and the problem is only with this implementation. Properly - gateway after couple first uplinks doesn't send New Channel Req to nodes. 
If there was a downlink from the gateway after each uplink, it completely clogs the network, my typical application has over a thousand sensors.
As I wrote in OTAA mode, your library is behaving correctly, the problem is only with ABP.

**Comment by dachalco** [comment]
@zzolax

Hmm, very strange. Can I ask which LoRa server you are using (ie. TTN, chirpstack, etc)? Are your other ABP end nodes also using this stack -- if they're not, which stack are they using?

**Comment by zzolax** [comment]
@dachalco I used i.e. LMIC library with AVR and RFM95W.  Server is built in RAK7258. I already asked RAK, they said problem is in node.
