### ISSUE TITLE
Has anyone used this with the InsightSIP 4520?

### ISSUE THREAD

**Issue by DrEdHepler** [FreeRTOS/Lab-Project-FreeRTOS-LoRaWAN#9]
Curious if anyone has used this project with the InsightSIP 4520.   I made some minor changes that represent the SPI pins used between the nRF52832 and the SX126x part, but haven't gotten past the initialization of the SX126x.   Seems as though the "Wakeup" SPI transfer (first SPI transfer) never completes.    Double checked the pin assignments, but all interconnections between the nRF52832 and SX126x in inside the InsightSIP module, so it makes debugging difficult...

Haven't used FreeRTOS in a couple of years, but it seems that there is more "overhead" between app SPI calls and the hardware than there was the last time I used it.    Back then, I just made calls directly to the Nordic nrfx library...   Just an observation...

Thanks!

**Comment by yanjos-dev** [comment]
Hi @DrEdHepler,

I don't have any prior experience with this platform. The [FreeRTOS forums](https://github.com/FreeRTOS/Lab-Project-FreeRTOS-LoRaWAN/issues/9) get more traffic than this repository. I suggest that you ask this question on the forums and see if you have more luck getting a response on there. I'll close this issue for now, but feel free to re-open the issue if you have any specific questions or issues pertaining to the library.
